name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./encyclopedia
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: encyclopedia/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build -- --configuration production
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseToken: '${{ secrets.FIREBASE_TOKEN }}'
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels