name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./encyclopedia
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: encyclopedia/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Install function dependencies
        run: npm ci --prefix ../functions
      - name: Build SSR bundle
        run: npm run build:ssr
      - name: Compile cloud function
        run: npm run compile:functions
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: 'luminary-universe'
          channelId: live
          entryPoint: ./encyclopedia
